[package]
name = "veil"
version = "0.1.0"
description = "Yet another 3DMigoto mod manager"
authors = ["vzpyr"]
edition = "2024"

[lib]
name = "veil_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "fs", "io-util", "macros"] }
futures-util = "0.3"
reqwest = { version = "0.13", features = ["stream", "json"] }
zip = { version = "2.2", default-features = false, features = ["deflate", "bzip2", "time"] }
bzip2 = { version = "0.5", default-features = false, features = ["libbz2-rs-sys"] }
sevenz-rust = "0.6"
unrar = "0.5"
sha2 = "0.11"
hex = "0.4"

[dev-dependencies]
tempfile = "3"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
