import { createTheme } from "@mantine/core";
import {
  veilDark,
  veilGray,
  veilWarning,
  veilError,
  veilSuccess,
  veilInfo,
  variantColorResolver,
} from "./colors";
import { components } from "./components";

export const theme = createTheme({
  primaryColor: "gray",
  primaryShade: { light: 6, dark: 2 },
  colors: {
    dark: veilDark,
    gray: veilGray,
    orange: veilWarning,
    yellow: veilWarning,
    red: veilError,
    green: veilSuccess,
    teal: veilSuccess,
    blue: veilInfo,
  },
  variantColorResolver,
  breakpoints: {
    xs: "36em",
    sm: "48em",
    md: "62em",
    lg: "75em",
    xl: "88em",
    xxl: "110em",
  },
  fontFamily: "var(--font-family-sans)",
  fontFamilyMonospace: "var(--font-family-mono)",
  defaultRadius: "md",
  cursorType: "pointer",
  shadows: {
    xs: "var(--shadow-xs)",
    sm: "var(--shadow-sm)",
    md: "var(--shadow-md)",
    lg: "var(--shadow-lg)",
    xl: "var(--shadow-lg)",
  },
  spacing: {
    "3xs": "var(--space-3xs)",
    "2xs": "var(--space-2xs)",
    xs: "var(--space-xs)",
    sm: "var(--space-sm)",
    md: "var(--space-md)",
    lg: "var(--space-lg)",
    xl: "var(--space-xl)",
    "2xl": "var(--space-2xl)",
    "3xl": "var(--space-3xl)",
  },
  radius: {
    xs: "var(--radius-xs)",
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    pill: "var(--radius-pill)",
  },
  fontSizes: {
    "3xs": "var(--font-size-3xs)",
    "2xs": "var(--font-size-2xs)",
    xs: "var(--font-size-xs)",
    sm: "var(--font-size-sm)",
    md: "var(--font-size-md)",
    lg: "var(--font-size-lg)",
    xl: "var(--font-size-xl)",
    "2xl": "var(--font-size-2xl)",
    "3xl": "var(--font-size-3xl)",
  },
  components,
});
